---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ./hosts.ini
  config_options:
    defaults:
      verbosity: 1
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint .
scenario:
  name: default
  converge_sequence:
    - prepare
    - converge
  test_sequence:
    - syntax
    - lint
    - prepare
    - converge
    - idempotence
    - verify
...